name: Sancar Adali
author: Herring Cove
markdown: redcarpet
pygments: false
baseurl: 
description: 
github: http://www.github.com/adalisan
twitter: http://www.twitter.com/adalisan
facebook: https://www.facebook.com/sancar.adali
linkedin: http://www.linkedin.com/pub/sancar-adali/3/a06/57b/
email: sadali[at]gmail.com
location: 
disqus: 

##Make sure to edit the above fields, especially for disqus.

